# Generated by Django 5.2.5 on 2025-08-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_visitorcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
    ]
