# Generated by Django 5.1.6 on 2025-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('lokasi', models.CharField(max_length=200)),
                ('kapasitas', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fasilitas/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermohonanPeminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pemohon', models.CharField(max_length=255)),
                ('alamat', models.CharField(max_length=500)),
                ('no_telepon', models.CharField(max_length=20)),
                ('email_pemohon', models.EmailField(max_length=254)),
                ('fasilitas_dipinjam', models.CharField(max_length=100)),
                ('tanggal_peminjaman', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('keperluan', models.TextField()),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak')], default='menunggu', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('penanggung_jawab', models.CharField(max_length=100)),
                ('fasilitas', models.ManyToManyField(to='kegiatan.fasilitas')),
            ],
        ),
    ]
