# Generated by Django 5.2.5 on 2025-08-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_visitorcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorcount',
            old_name='total_visits',
            new_name='count',
        ),
    ]
