# Generated by Django 5.2.5 on 2025-08-23 13:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0003_rename_total_visits_visitorcount_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorcount',
            name='last_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitorcount',
            name='total_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
